### ISSUE TITLE
App crashes after Clicking on stop sharing 

### ISSUE THREAD

**Issue by savannahar68** [Pranav2612000/distrideochat#61] opened 2020-05-23 16:19 UTC
![image](https://user-images.githubusercontent.com/20986069/82735413-37a0b180-9d3f-11ea-884d-3b385508f363.png)

**Comment by veddandekar** [comment] 2020-05-24 09:27
Although I was unable to reproduce this issue, I did find a possible cause for it. The same has been fixed and merged. 
Could you check if this issue has been solved? If not resolved, then please provide the steps to reproduce.

**Comment by Pranav2612000** [comment] 2020-05-25 05:27
@veddandekar 
Is this issue solved?

**Closed by Pranav2612000** 2020-05-25 05:27 UTC

**Comment by savannahar68** [comment] 2020-05-25 05:36
@Pranav2612000 @veddandekar 
So the stop sharing button is lost while merging other branches

This issue was seen after clicking on stop sharing button!
We can reproduce it by going by to commit 4 days ago and then trying stop sharing

Open the issue, as even if right now we don't have stop sharing button we'll need to add it as it is essential!
